name: Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Requirements
      run: python -m pip install -r dev-requirements.txt

    # https://github.com/python/mypy/issues/10600
    - name: Setup mypy
      run: mkdir .mypy_cache

    - name: Run lint script
      run: python project.py lint
